@section('sidebar-nav')
    <a href="{{ route('home') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm text-slate-600 hover:bg-slate-50 hover:text-primary transition-colors"><span class="material-symbols-outlined text-[20px]">home</span>Browse</a>
    <a href="{{ route('seller.dashboard') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('seller.dashboard') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">dashboard</span>Dashboard</a>
    <a href="{{ route('seller.ads') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('seller.ads', 'seller.promote') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">list_alt</span>My Ads</a>
    <a href="{{ route('seller.campaigns') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('seller.campaigns') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">campaign</span>Pro Sales</a>
    <a href="{{ route('ads.create') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('ads.create') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">add_circle</span>Post Ad</a>
    <a href="{{ route('chat.index') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('chat.*') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">chat</span>Messages</a>
    <a href="{{ route('profile.edit') }}" class="flex items-center gap-3 px-4 py-2.5 rounded-xl font-medium text-sm {{ request()->routeIs('profile.*') ? 'bg-primary/10 text-primary' : 'text-slate-600 hover:bg-slate-50 hover:text-primary' }} transition-colors"><span class="material-symbols-outlined text-[20px]">manage_accounts</span>Profile</a>
@endsection

@section('mobile-nav')
    <a href="{{ route('home') }}" class="flex flex-col items-center gap-0.5 text-slate-500 text-xs"><span class="material-symbols-outlined text-[22px]">home</span>Home</a>
    <a href="{{ route('seller.dashboard') }}" class="flex flex-col items-center gap-0.5 {{ request()->routeIs('seller.dashboard') ? 'text-primary font-medium' : 'text-slate-500' }} text-xs"><span class="material-symbols-outlined text-[22px]">dashboard</span>Dash</a>
    <a href="{{ route('seller.ads') }}" class="flex flex-col items-center gap-0.5 {{ request()->routeIs('seller.ads', 'seller.promote') ? 'text-primary font-medium' : 'text-slate-500' }} text-xs"><span class="material-symbols-outlined text-[22px]">list_alt</span>Ads</a>
    <a href="{{ route('seller.campaigns') }}" class="flex flex-col items-center gap-0.5 {{ request()->routeIs('seller.campaigns') ? 'text-primary font-medium' : 'text-slate-500' }} text-xs"><span class="material-symbols-outlined text-[22px]">campaign</span>Pro</a>
    <a href="{{ route('ads.create') }}" class="flex flex-col items-center gap-0.5 -mt-4 text-xs"><div class="bg-primary text-white rounded-full p-3 shadow-lg border-4 border-white"><span class="material-symbols-outlined text-[24px]">add</span></div><span class="text-slate-500">Post</span></a>
@endsection
